# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LOPART_interface <- function(input_data, input_label_start, input_label_end, input_label_changes, penalty) {
    .Call(`_LOPART_LOPART_interface`, input_data, input_label_start, input_label_end, input_label_changes, penalty)
}

